require 'whyvalidationssuckin96'
require 'active_record'
require 'whyvalidationssuckin96/rails/active_record/base_validation_overrides'
require 'whyvalidationssuckin96/rails/active_record/association_validation'
require 'whyvalidationssuckin96/rails/macros'